name: Publish to PyPI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
    - name: Test
      run: make test

    - name: Configure Git
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "action@github.com"

    - name: Build and publish
      # First make the commit for the release, tag requirements updates and changelog
      run: |
        poetry run semantic-release version
        poetry export --dev -f requirements.txt > requirements.txt
        printf "## %s\n%s\n\n%s\n" "$(git tag --sort=taggerdate | tail -1)" "$(poetry run semantic-release changelog)" "$(cat CHANGELOG.md)" > CHANGELOG.md
        git commit -a --amend --no-edit
        poetry build
        poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
  
    - name: Push to git
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: true
